
"""
Tanvi's Y2K Affirmation Rush
A retro Y2K-styled typing game built with Tkinter.
Run: python tanvi_y2k_game.py
Author: Generated by ChatGPT for Tanvi Koranne
"""

import tkinter as tk
import time
import math
import random

# --- Configuration ---
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 650
BG_GRADIENT_TOP = "#0f0f3a"
BG_GRADIENT_BOTTOM = "#3b0b4b"
PALETTE = {
    "maroon": "#780000",
    "cream": "#EDEDE9",
    "neon": "#00ffd5",
    "hotpink": "#ff31b4",
    "chrome": "#cfd8dc",
    "black": "#000000",
    "white": "#ffffff"
}

TASKS = [
    ("Agency Launch: L’egitimate becomes the Ogilvy of Instagram", "I build L'egitimate into the Ogilvy of Instagram for small businesses."),
    ("Streetwear Drop: L'Ether 'Fuel the Future' capsule", "I launch L'Ether — streetwear that fuses trucking grit with fashion."),
    ("Podcast Growth: The L'egit Pod reaches listeners", "My podcast connects creators with ideas; it grows weekly."),
    ("IIMK Rebrand: Campus page refreshed and energized", "I rebrand the IIMK Kochi Campus page to attract future students."),
    ("Fashion Week: Invited & showcased", "I walk the runway and present my streetwear at Fashion Week."),
    ("Scholarship: Win the top scholarship", "I win the scholarship for academic and creative excellence."),
    ("Top Grades: Batch topper", "I become number one in the batch in terms of grades.")
]

# WPM thresholds per task (encourage faster typing for harder tasks)
WPM_TARGETS = [45, 50, 40, 42, 55, 60, 65]

# --- Utility functions ---
def gradient_rect(canvas, x1, y1, x2, y2, color1, color2, steps=50):
    # vertical gradient using rectangles
    r1 = int(color1[1:3],16); g1 = int(color1[3:5],16); b1 = int(color1[5:7],16)
    r2 = int(color2[1:3],16); g2 = int(color2[3:5],16); b2 = int(color2[5:7],16)
    for i in range(steps):
        r = int(r1 + (r2-r1) * (i/steps))
        g = int(g1 + (g2-g1) * (i/steps))
        b = int(b1 + (b2-b1) * (i/steps))
        color = f'#{r:02x}{g:02x}{b:02x}'
        y = y1 + (y2-y1)*(i/steps)
        canvas.create_rectangle(x1, y, x2, y + (y2-y1)/steps + 1, outline='', fill=color)

# --- Game Class ---
class Y2KGame:
    def __init__(self, root):
        self.root = root
        root.title("Tanvi's Y2K Affirmation Rush")
        root.geometry(f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}")
        root.resizable(False, False)

        self.canvas = tk.Canvas(root, width=WINDOW_WIDTH, height=WINDOW_HEIGHT, highlightthickness=0)
        self.canvas.pack(fill="both", expand=True)

        # Draw background gradient and Y2K elements
        gradient_rect(self.canvas, 0, 0, WINDOW_WIDTH, WINDOW_HEIGHT, BG_GRADIENT_TOP, BG_GRADIENT_BOTTOM)

        # Floating chrome header bar
        self.canvas.create_rounded_rect = self.create_rounded_rect  # attach helper
        self.canvas.create_rounded_rect(60, 30, WINDOW_WIDTH-60, 110, 18, fill=PALETTE["chrome"], outline='')

        # Title
        self.canvas.create_text(WINDOW_WIDTH//2, 60, text="TANVI'S Y2K AFFIRMATION RUSH", font=("Helvetica", 22, "bold"), fill=PALETTE["maroon"])

        # Subtitle / instructions
        instr_text = ("Type each affirmation as fast and accurately as you can.\n"
                      "Speed (WPM) + Accuracy unlocks achievements: Fashion Week, Scholarship, Top Grades.")
        self.canvas.create_text(WINDOW_WIDTH//2, 92, text=instr_text, font=("Helvetica", 10), fill=PALETTE["black"])

        # Task area panel
        self.panel_x1, self.panel_y1 = 80, 140
        self.panel_x2, self.panel_y2 = WINDOW_WIDTH - 80, 420
        self.canvas.create_rectangle(self.panel_x1, self.panel_y1, self.panel_x2, self.panel_y2, fill="#0a0a22", outline=PALETTE["maroon"], width=3)

        # Sparkles / Y2K decorations (animated)
        self.sparkles = [self.random_sparkle() for _ in range(18)]

        # Game state
        self.current_task_index = 0
        self.start_time = None
        self.typed_chars = ""
        self.score = 0
        self.task_results = [False]*len(TASKS)

        # Input box
        self.user_input = tk.StringVar()
        self.entry = tk.Entry(root, textvariable=self.user_input, font=("Consolas", 14), width=70, bg="#111", fg=PALETTE["neon"], insertbackground=PALETTE["neon"])
        self.entry_window = self.canvas.create_window(WINDOW_WIDTH//2, 500, window=self.entry)
        self.entry.bind("<KeyRelease>", self.on_type)

        # Buttons
        self.submit_button = tk.Button(root, text="Submit Affirmation", command=self.submit_affirmation, bg=PALETTE["maroon"], fg="white", font=("Helvetica", 11, "bold"))
        self.canvas.create_window(WINDOW_WIDTH//2 + 240, 500, window=self.submit_button)

        self.skip_button = tk.Button(root, text="Skip (Take a Breather)", command=self.skip_task, bg=PALETTE["hotpink"], fg="white", font=("Helvetica", 9, "bold"))
        self.canvas.create_window(WINDOW_WIDTH//2 - 240, 500, window=self.skip_button)

        # HUD: tasks list and progress
        self.render_task_list()
        self.update_loop()

        # Achievements panel
        self.achievements = {"Fashion Week": False, "Scholarship": False, "Top Grades": False}
        self.render_achievements()

        # Start prompt
        self.display_current_task()

        # Focus input
        self.entry.focus_set()

    def random_sparkle(self):
        return {"x": random.randint(self.panel_x1+20, self.panel_x2-20),
                "y": random.randint(self.panel_y1+20, self.panel_y2-20),
                "size": random.uniform(2,6),
                "phase": random.random()*2*math.pi,
                "speed": random.uniform(0.01, 0.04)}

    def create_rounded_rect(self, x1, y1, x2, y2, r=12, **kwargs):
        points = [x1+r, y1,
                  x2-r, y1,
                  x2, y1,
                  x2, y1+r,
                  x2, y2-r,
                  x2, y2,
                  x2-r, y2,
                  x1+r, y2,
                  x1, y2,
                  x1, y2-r,
                  x1, y1+r,
                  x1, y1]
        return self.canvas.create_polygon(points, smooth=True, **kwargs)

    def render_task_list(self):
        # Left side: task titles
        x = self.panel_x1 + 20
        y = self.panel_y1 + 20
        self.canvas.delete("task_list")
        for i, (title, aff) in enumerate(TASKS):
            color = PALETTE["neon"] if i == self.current_task_index else PALETTE["white"]
            status = "✓" if self.task_results[i] else "·"
            self.canvas.create_text(x, y + i*34, anchor="nw", text=f"{status} {title}", font=("Helvetica", 12, "bold"), fill=color, tags="task_list")

    def display_current_task(self):
        # Show task card in panel center
        self.canvas.delete("task_card")
        title, aff = TASKS[self.current_task_index]
        cx = (self.panel_x1 + self.panel_x2)//2
        cy = self.panel_y1 + 60
        # Card background
        self.canvas.create_rectangle(cx-360, cy-40, cx+360, cy+120, fill="#060616", outline=PALETTE["hotpink"], width=2, tags="task_card")
        # Title
        self.canvas.create_text(cx, cy-18, text=title, font=("Helvetica", 16, "bold"), fill=PALETTE["cream"], tags="task_card")
        # Affirmation (wrapped)
        self.canvas.create_text(cx, cy+12, text=aff, font=("Consolas", 12), fill=PALETTE["white"], width=640, tags="task_card")
        # WPM target
        wpm_target = WPM_TARGETS[self.current_task_index]
        self.canvas.create_text(cx+300, cy+12, text=f"Target: {wpm_target} WPM", font=("Helvetica", 10, "italic"), fill=PALETTE["chrome"], tags="task_card")
        # Progress ring area
        self.draw_progress_ring(cx+360, cy+60, 36, progress= self.calculate_overall_progress(), tag="task_card")

    def draw_progress_ring(self, x, y, r, progress=0.0, tag=""):
        # background circle
        self.canvas.create_oval(x-r, y-r, x+r, y+r, outline=PALETTE["cream"], width=3, tags=tag)
        # progress arc
        extent = progress * 360
        if extent > 0:
            self.canvas.create_arc(x-r, y-r, x+r, y+r, start=90, extent=-extent, style="arc", outline=PALETTE["neon"], width=6, tags=tag)
        # center text
        self.canvas.create_text(x, y, text=f"{int(progress*100)}%", font=("Helvetica", 9, "bold"), fill=PALETTE["cream"], tags=tag)

    def calculate_overall_progress(self):
        return sum(1 for x in self.task_results if x)/len(self.task_results)

    def on_type(self, event=None):
        # start timer when user begins typing for current task
        if self.start_time is None and self.user_input.get().strip() != "":
            self.start_time = time.time()
        # update typed chars for live WPM (if needed)
        self.typed_chars = self.user_input.get()

    def submit_affirmation(self):
        text = self.user_input.get().strip()
        if not text:
            return
        # compute speed and accuracy
        elapsed = max(0.01, time.time() - (self.start_time or time.time()))
        words = len(text.split())
        wpm = words / (elapsed/60)
        # check similarity / accuracy (simple metric)
        target_aff = TASKS[self.current_task_index][1].lower()
        accuracy = self.compute_accuracy(text.lower(), target_aff)
        # scoring: weighted by wpm and accuracy
        score_val = int(wpm * accuracy * 0.1)
        success = (wpm >= WPM_TARGETS[self.current_task_index] and accuracy >= 0.7)
        self.task_results[self.current_task_index] = success
        self.score += score_val
        self.show_result_popup(wpm, accuracy, success)
        # reset input and timer
        self.user_input.set("")
        self.start_time = None
        self.typed_chars = ""
        # update achievements
        self.check_achievements()
        self.render_task_list()
        self.display_current_task()

    def skip_task(self):
        # allow skipping to next task (for pacing)
        self.current_task_index = (self.current_task_index + 1) % len(TASKS)
        self.render_task_list()
        self.display_current_task()
        self.user_input.set("")
        self.start_time = None

    def compute_accuracy(self, typed, target):
        # character-level similarity (Levenshtein distance approximation)
        # simple implementation of normalized edit distance
        return 1 - (self.levenshtein_distance(typed, target) / max(len(target), 1))

    def levenshtein_distance(self, s, t):
        # dynamic programming
        if s == t: return 0
        rows = len(s)+1
        cols = len(t)+1
        dist = [[0]*cols for _ in range(rows)]
        for i in range(1, rows): dist[i][0] = i
        for j in range(1, cols): dist[0][j] = j
        for i in range(1, rows):
            for j in range(1, cols):
                cost = 0 if s[i-1]==t[j-1] else 1
                dist[i][j] = min(dist[i-1][j]+1, dist[i][j-1]+1, dist[i-1][j-1]+cost)
        return dist[-1][-1]

    def show_result_popup(self, wpm, accuracy, success):
        popup = tk.Toplevel(self.root)
        popup.geometry("420x200")
        popup.title("Result")
        popup.transient(self.root)
        msg = f"WPM: {int(wpm)}\nAccuracy: {int(accuracy*100)}%"
        result_text = "Success! Task completed." if success else "Nice try — keep practicing!"
        colors = ("#0b3d0b","#2d2d2d")
        label = tk.Label(popup, text=result_text, font=("Helvetica", 14, "bold"), fg=PALETTE["maroon"])
        label.pack(pady=12)
        tk.Label(popup, text=msg, font=("Consolas", 12)).pack(pady=6)
        tk.Button(popup, text="Continue", command=popup.destroy, bg=PALETTE["neon"]).pack(pady=10)
        # confetti if success
        if success:
            self.popup_confetti(popup)

    def popup_confetti(self, popup):
        c = tk.Canvas(popup, width=400, height=90, bg="#111")
        c.pack()
        pieces = []
        for _ in range(32):
            x = random.randint(0, 400)
            y = random.randint(0, 90)
            color = random.choice([PALETTE["neon"], PALETTE["hotpink"], PALETTE["chrome"], PALETTE["cream"]])
            pieces.append(c.create_rectangle(x, y, x+6, y+8, fill=color, outline=""))
        def fall():
            for i, p in enumerate(pieces):
                c.move(p, 0, random.randint(2,6))
            popup.after(80, fall)
        fall()

    def check_achievements(self):
        # achievements based on specific task results
        # Fashion Week unlocked if streetwear and agency tasks are success
        if self.task_results[1] and self.task_results[0]:
            self.achievements["Fashion Week"] = True
        if self.task_results[5] and sum(self.task_results) >= 4:
            self.achievements["Scholarship"] = True
        if self.task_results[6] and all(self.task_results[:4]):
            self.achievements["Top Grades"] = True
        self.render_achievements()

    def render_achievements(self):
        # right side achievement panel
        ax1, ay1, ax2, ay2 = WINDOW_WIDTH-260, 140, WINDOW_WIDTH-80, 420
        self.canvas.delete("ach_panel")
        self.canvas.create_rectangle(ax1, ay1, ax2, ay2, fill="#071224", outline=PALETTE["hotpink"], width=2, tags="ach_panel")
        self.canvas.create_text((ax1+ax2)//2, ay1+18, text="ACHIEVEMENTS", font=("Helvetica", 12, "bold"), fill=PALETTE["cream"], tags="ach_panel")
        y = ay1+46
        for name, unlocked in self.achievements.items():
            color = PALETTE["neon"] if unlocked else PALETTE["chrome"]
            status = "UNLOCKED" if unlocked else "Locked"
            self.canvas.create_text(ax1+12, y, anchor="w", text=f"• {name}", font=("Helvetica", 11, "bold"), fill=color, tags="ach_panel")
            self.canvas.create_text(ax2-12, y, anchor="e", text=status, font=("Helvetica", 9), fill=color, tags="ach_panel")
            y += 34

    def update_loop(self):
        # animate sparkles
        self.canvas.delete("sparkle")
        for s in self.sparkles:
            s["phase"] += s["speed"]
            yoff = math.sin(s["phase"]) * 6
            size = s["size"] + (math.sin(s["phase"]*2)+1)*0.7
            self.canvas.create_oval(s["x"]-size, s["y"]-size+yoff, s["x"]+size, s["y"]+size+yoff, fill=PALETTE["hotpink"], outline="", tags="sparkle")
        # cursor WPM live preview
        self.canvas.delete("live_wpm")
        live_wpm = 0
        if self.start_time and self.typed_chars:
            elapsed = max(0.01, time.time() - self.start_time)
            live_wpm = int(len(self.typed_chars.split()) / (elapsed/60))
        self.canvas.create_text(WINDOW_WIDTH//2, 470, text=f"Live WPM: {live_wpm}", font=("Consolas", 11), fill=PALETTE["chrome"], tags="live_wpm")
        # draw small animated chrome edges
        for i in range(4):
            dx = (math.sin(time.time()*1.2 + i)*4)
            self.canvas.create_line(60+dx, 120, 140+dx, 120, fill=PALETTE["hotpink"], width=2, tags="sparkle")
        # loop
        self.root.after(70, self.update_loop)

# --- Main ---
def main():
    root = tk.Tk()
    # attach helper to canvas tk to support rounded rectangle on creation (monkey patch for aesthetics)
    app = Y2KGame(root)
    root.mainloop()

if __name__ == "__main__":
    main()
